### ISSUE TITLE
关于lxp显示数据不及时的问题

### ISSUE THREAD

**Issue by sxf123333** [Consensys/doc.linea#751]
### Describe the bug

lxp显示数据不及时的问题

### Steps to reproduce

lxp显示数据不及时的问题

### Expected behavior

lxp显示数据不及时的问题

### Link

lxp显示数据不及时的问题

**Comment by jlwllmr** [comment]
From what I can understand via Google Translate, you're having an issue with your LXP balance? I'll close since this isn't a docs-related issue or request. If you need and support, please use the chat on our [support page](https://support.linea.build/) or use our moderated [Discord](https://discord.gg/linea).
